version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: python -m my_api
